import mongoose from "mongoose";

const nocSchema = new mongoose.Schema(
  {
    // ------------------------------------------------------------
    // Application
    // ------------------------------------------------------------

    application: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "StudentApplication",
      required: true,
      unique: true,
      index: true,
    },

    // ------------------------------------------------------------
    // Student
    // ------------------------------------------------------------

    student: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Student",
      required: true,
      index: true,
    },

    // ------------------------------------------------------------
    // Organisation
    // ------------------------------------------------------------

    organisation: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Organisation",
      required: true,
      index: true,
    },

    // ------------------------------------------------------------
    // NOC Reference Number
    // ------------------------------------------------------------

    referenceNumber: {
      type: String,
      required: true,
      unique: true,
      index: true,
      uppercase: true,
      trim: true,
    },

    // ------------------------------------------------------------
    // Generated By
    // ------------------------------------------------------------

    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    generatedAt: {
      type: Date,
      default: Date.now,
    },

    // ------------------------------------------------------------
    // Academic Information
    // ------------------------------------------------------------

    academicYear: {
      type: Number,
      required: true,
    },

    department: {
      type: String,
      required: true,
      trim: true,
    },

    // ------------------------------------------------------------
    // Server File Information
    // ------------------------------------------------------------

    fileName: {
      type: String,
      required: true,
      trim: true,
    },

    /*
     * Internal filesystem path.
     *
     * Example:
     *
     * uploads/nocs/2026/IT/NOC-TNP_JGEC_INT_2026_IT_001.pdf
     */
    filePath: {
      type: String,
      required: true,
      trim: true,
    },

    /*
     * Backend URL used by frontend.
     *
     * Example:
     *
     * /applications/spoc/6ac66989907c592d4721d4f0/noc/pdf
     */
    fileUrl: {
      type: String,
      required: true,
      trim: true,
    },

    fileMimeType: {
      type: String,
      default: "application/pdf",
      trim: true,
    },

    fileSize: {
      type: Number,
      default: 0,
    },

    // ------------------------------------------------------------
    // Status
    // ------------------------------------------------------------

    status: {
      type: String,
      enum: ["generated", "revoked"],
      default: "generated",
      index: true,
    },

    revokedAt: {
      type: Date,
      default: null,
    },

    revokeReason: {
      type: String,
      trim: true,
      maxlength: 1000,
      default: "",
    },
  },
  {
    timestamps: true,
  },
);

export const NOC = mongoose.model("NOC", nocSchema);
